### ISSUE TITLE
Kernel keeps crashing

### ISSUE THREAD

**Issue by Chandrapenta** [sumantrajoshi/Face-recognition-using-deep-learning#3]
kernel keeps crashing while running the "# Lets run the face recognizer program :-)" section.
<img width="1342" alt="Screenshot 2019-07-26 at 14 09 09" src="https://user-images.githubusercontent.com/53342233/61953727-118b7300-afaf-11e9-964b-0310723ae48f.png">

**Comment by Chandrapenta** [comment]
solved by creating virtual environment for running my notebook from it.

**Comment by RaviGprec** [comment]
I'm running it on colab editor. The colab editor is being crashed with below error:
